FinalProject/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProject.Controllers
{
	public class AboutController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

FinalProject/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProject.Data;
using FinalProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json.Linq;
using System.Net.Http;

namespace FinalProject.Controllers
{
    public class OrdersController : Controller
    {
        static HttpClient client = new HttpClient();
        private readonly FinalProjectContext _context;

        public OrdersController(FinalProjectContext context)
        {
            _context = context;
        }

        // GET: Orders
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string Address, string price)
        {

            var finalProjectContext = from o in _context.Orders
                                      join u in _context.Users
                                      on o.UsersId equals u.Id
                                      select new Orders
                                      {
                                          Id = o.Id,
                                          UsersId = o.UsersId,
                                          User = u,
                                          Address = o.Address,
                                          OrderPrice = o.OrderPrice,
                                          OrderDate = o.OrderDate,
                                      };
            return View(await finalProjectContext.ToListAsync());
        }

        // GET: Orders/Details/5
        [Authorize(Roles = "Admin, Editor, Client")]
        public async Task<IActionResult> MyOrders()
        {
                var path = "http://data.fixer.io/api/latest?access_key=758b556a8a2bc33fafde24780c31dbea&symbols=USD,CAD,JPY";
                var wether = "";
                HttpResponseMessage response = await client.GetAsync(path);
                if (response.IsSuccessStatusCode)
                {
                    wether = response.Content.ReadAsStringAsync().Result;
                    var ssss = Newtonsoft.Json.JsonConvert.DeserializeObject(wether);
                    ViewBag.wether = ssss;
                var a = "";
            }
                
            

            var userId = Convert.ToInt32(HttpContext.Session.GetString("Userid"));

            var myOrders = _context.Orders.Include(o => o.OrderDetails).ThenInclude(od => od.Product).Where(m => m.UsersId == userId);

            return View(await myOrders.ToListAsync());
        }

        public async Task<bool> CreateOrder(string address)
        {
            var orderPrice = 0.0;
            Orders order = new();
            order.UsersId = int.Parse(HttpContext.Session.GetString("Userid"));
            order.Address = address;
            order.OrderDate = DateTime.Now;

            JObject dynamicCart = JObject.Parse(HttpContext.Session.GetString("cart"));
            var numOfOD = 0;
            foreach (var property in dynamicCart)
            {
                if (int.Parse(property.Value.ToString()) > 0)
                {
                    numOfOD++;
                    var product = from p in _context.Products
                                  where p.Id == int.Parse(property.Key)
                                  select p;

                    orderPrice += product.First().Price * int.Parse(property.Value.ToString());
                }
            }
            if (numOfOD > 0) 
            {
                order.OrderPrice = orderPrice;
                _context.Add(order);
                await _context.SaveChangesAsync();
                var orderDetailsRange = new OrderDetails[numOfOD];
                var id = 0;
                foreach (var property in dynamicCart)
                {
                    if (int.Parse(property.Value.ToString()) > 0)
                    {

                        orderDetailsRange[id] = new();
                        orderDetailsRange[id].ProductsId = int.Parse(property.Key);
                        orderDetailsRange[id].Amount = int.Parse(property.Value.ToString());
                        orderDetailsRange[id].OrdersId = order.Id;
                        id++;
                    }
                }
                _context.AddRange(orderDetailsRange);
                await _context.SaveChangesAsync();
            } else
            {
                return false;
            }
            HttpContext.Session.Remove("cart");
            return true;
        }

        // GET: Orders/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders.FindAsync(id);
            if (orders == null)
            {
                return NotFound();
            }
            ViewData["UsersId"] = new SelectList(_context.Users, "Id", "Id", orders.UsersId);
            return View(orders);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UsersId,Address,OrderPrice,OrderDate")] Orders orders)
        {
            if (id != orders.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orders);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrdersExists(orders.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UsersId"] = new SelectList(_context.Users, "Id", "Id", orders.UsersId);
            return View(orders);
        }

        // GET: Orders/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orders = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(orders);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        
        private bool OrdersExists(int id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }
    }
}

FinalProject/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProject.Data;
using FinalProject.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace FinalProject.Controllers
{
    public class UsersController : Controller
    {
        private readonly FinalProjectContext _context;

        public UsersController(FinalProjectContext context)
        {
            _context = context;
        }

        // GET: Users/Login
        public IActionResult Login()
        {
            if (HttpContext.Session.GetString("Permission") != null)
            {
                return RedirectToAction(nameof(Index), "Products");
            }
            ViewData["PermissionsId"] = new SelectList(_context.Permissions, "Id", "PermissionName");
            return View();
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        // POST: Users/Login
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([Bind("Id,Username,Password")] Users users)
        {
            var q = from user in _context.Users
                    where user.Username == users.Username && user.Password == users.Password
                    select user;

            if (q.Count() > 0)
            {
                Signin(q.First());

                return RedirectToAction(nameof(Index), "Products");
            }
            else
            {
                ViewData["Error"] = "Sorry, username and/or password are incorrect!";
            }
            ViewData["PermissionsId"] = new SelectList(_context.Permissions, "Id", "PermissionName", users.PermissionsId);
            return View(users);
        }

        private async void Signin(Users account)
        {
            var permission = from permissions in _context.Permissions
                             where permissions.Id == account.PermissionsId
                             select permissions;

            HttpContext.Session.SetString("Permission", permission.First().PermissionName);
            HttpContext.Session.SetString("Username", account.Username);
            HttpContext.Session.SetString("Userid", account.Id.ToString());
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, account.Username),
                new Claim(ClaimTypes.Role, permission.First().PermissionName),
            };

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties
            {
                ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10)
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);
        }

        public async Task<IActionResult> Signout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Clear();

            return RedirectToAction("Login");
        }

        // GET: Users/Register
        public IActionResult Register()
        {
            if (HttpContext.Session.GetString("Permission") != null)
            {
                return RedirectToAction(nameof(Index), "Products");
            }
            ViewData["PermissionsId"] = new SelectList(_context.Permissions, "Id", "PermissionName");
            return View();
        }

        // POST: Users/Register
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register([Bind("Id,Fullname,Username,Password,Email,Birthdate")] Users users)
        {
            if (ModelState.IsValid)
            {
                var username = _context.Users.FirstOrDefault(user => user.Username == users.Username);

                if (username == null)
                {
                    var email = _context.Users.FirstOrDefault(user => user.Email == users.Email);
                    if (email == null)
                    {
                        _context.Add(users);
                        await _context.SaveChangesAsync();

                        var newUser = _context.Users.FirstOrDefault(user => user.Username == users.Username && user.Password == users.Password);

                        Signin(newUser);

                        return RedirectToAction(nameof(Index), "Products");
                    } else
                    {
                        ViewData["Error"] = "Email is not available";
                    }

                }
                else
                {
                    ViewData["Error"] = "Username is not available";
                }
            }
            ViewData["PermissionsId"] = new SelectList(_context.Permissions, "Id", "PermissionName", users.PermissionsId);
            return View(users);
        }


        [HttpGet]
        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (HttpContext.Session.GetString("Userid") == null)
            {
                return View("Login");
            }

            if (HttpContext.Session.GetString("Permission") != "Admin" &&
                int.Parse(HttpContext.Session.GetString("Userid")) != id)
            {
                return View("AccessDenied");
            }
            var users = await _context.Users
                .Include(u => u.Permission)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        // GET: Users
        [Authorize(Roles = "Admin")]
        public async Task<ViewResult> Index(string username, string fullname, string email)
        {
            var users = await _context.Users.Where(u => (!String.IsNullOrEmpty(username) ? u.Username.ToLower().Contains(username.ToLower()) : true) &&
                                                  (!String.IsNullOrEmpty(fullname) ? u.Fullname.ToLower().Contains(fullname.ToLower()) : true) &&
                                                  (!String.IsNullOrEmpty(email) ? u.Email.ToLower().Contains(email.ToLower()) : true)).ToListAsync();
            return View( users);
        }


        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (HttpContext.Session.GetString("Userid") == null)
            {
                return View("Login");
            }

            if (HttpContext.Session.GetString("Permission") != "Admin" &&
                int.Parse(HttpContext.Session.GetString("Userid")) != id)
            {
                return View("AccessDenied");
            }

            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.Users.FindAsync(id);
            if (users == null)
            {
                return NotFound();
            }
            ViewData["PermissionsId"] = new SelectList(_context.Permissions, "Id", "PermissionName", users.PermissionsId);
            return View(users);
        }
        
                // POST: Users/Edit/5
                // To protect from overposting attacks, enable the specific properties you want to bind to.
                // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
                [HttpPost]
                [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Fullname,Username,Password,Email,Birthdate,PermissionsId")] Users users)
                {
                    if (id != users.Id)
                    {
                        return NotFound();
                    }

                    if (ModelState.IsValid)
                    {
                        try
                        {
                            _context.Update(users);
                            await _context.SaveChangesAsync();
                        }
                        catch (DbUpdateConcurrencyException)
                        {
                            if (!UsersExists(users.Id))
                            {
                                return NotFound();
                            }
                            else
                            {
                                throw;
                            }
                        }
                        return RedirectToAction(nameof(Index), "Products");
                    }
                    ViewData["PermissionsId"] = new SelectList(_context.Permissions, "Id", "PermissionName", users.PermissionsId);
                    return View(users);
                }

        // GET: Users/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
                {
                    if (id == null)
                    {
                        return NotFound();
                    }

                    var users = await _context.Users
                        .Include(u => u.Permission)
                        .FirstOrDefaultAsync(m => m.Id == id);
                    if (users == null)
                    {
                        return NotFound();
                    }

                    return View(users);

FinalProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinalProject</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/branches.css" />
    <link rel="stylesheet" href="~/css/utilities.css" />
    <link rel="stylesheet" href="~/css/products.css" type="text/css" />

    <style type="text/css">
        .notification {
            color: black;
            text-decoration: none;
            padding: 5px 10px;
            position: relative;
            display: inline-block;
            border-radius: 2px;
        }

            .notification .badge {
                position: absolute;
                padding: 2px 5px;
                border-radius: 50%;
                background: red;
                color: white;
            }
    </style>
</head>

<body>

    <script type="text/javascript">
        window.onload = function () {
            var ctx = document.querySelector("canvas").getContext("2d"),
                dashLen = 80, dashOffset = dashLen, speed = 5,
                txt = "FinalProject", x = 50, i = 0;

            ctx.font = "20px Comic Sans MS, cursive, TSCu_Comic, sans-serif";
            ctx.lineWidth = 0; ctx.lineJoin = "round"; ctx.globalAlpha = 2 / 3;
            ctx.strokeStyle = ctx.fillStyle = "black";

            (function loop() {
                ctx.clearRect(x, 40, 50, 50);
                ctx.setLineDash([dashLen - dashOffset, dashOffset - speed]); // create a long dash mask
                dashOffset -= speed;                                         // reduce dash length
                ctx.strokeText(txt[i], x, 20);                               // stroke letter

                if (dashOffset > 0) requestAnimationFrame(loop);             // animate
                else {
                    ctx.fillText(txt[i], x, 20);                               // fill final letter
                    dashOffset = dashLen;                                      // prep next char
                    x += ctx.measureText(txt[i++]).width + ctx.lineWidth * Math.random();
                    ctx.setTransform(1, 0, 0, 1, 0, 3 * Math.random());        // random y-delta
                    ctx.rotate(Math.random() * 0.005);                         // random rotation
                    if (i < txt.length) requestAnimationFrame(loop);
                }
            })();
        }
    </script>

    <header style="position:fixed;width:100%;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Products" asp-action="Index" >
                    <canvas id="myCanvas" width="200" height="30">
                        Your browser does not support the HTML canvas tag.
                    </canvas>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.Session.GetString("Permission") != null)
                        {
                            <li class="nav-item">
                                <a class="notification text-dark" asp-controller="Products" asp-action="ShoppingCart">
                                    <i class="bi bi-cart" style="font-size: 1.2rem;"></i>
                                    <span>cart</span>
                                </a>
                            </li>
                            <li class="nav-item ms-auto dropdown show">
                                <a class="nav-link text-dark dropdown-toggle" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Hello, @Context.Session.GetString("Username")
                                </a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" asp-controller="Users" asp-action=Details asp-route-id="@Context.Session.GetString("Userid")">User Details</a>
                                    <a class="dropdown-item" asp-controller="Orders" asp-action=MyOrders asp-route-id="2">My Orders</a>
                                    @if (Context.Session.GetString("Permission") == "Admin" ||
                                  Context.Session.GetString("Permission") == "Editor")
                                    {
                                        <hr />
                                        <a class="dropdown-item" asp-controller="Products" asp-action="Create">Add Product</a>
                                        <a class="dropdown-item" asp-controller="Categories" asp-action="Index">Manage Categories</a>
                                    }

                                    @if (Context.Session.GetString("Permission") == "Admin")
                                    {
                                        <a class="dropdown-item" asp-controller="Users" asp-action="Index">Manage Users</a>
                                        <a class="dropdown-item" asp-controller="Orders" asp-action="Index">Manage Orders</a>
                                    }
                                    <hr />
                                    <a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="Signout">Logout</a>
                                </div>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container" style="padding-top:70px;overflow:hidden;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="position:fixed;background-color:#fff; height: 60px">
		<div class="row">
			<center class="col-4">
				<a style="text-decoration: none" class=" text-dark" asp-area="" asp-controller="About" asp-action="Index">About</a>
			</center>
				<center class="col-4">
					<a style="text-decoration: none" class=" text-dark" asp-area="" asp-controller="Branches" asp-action="Index">Store Branches</a>
				</center>
				@if (Context.Session.GetString("Permission") == "Admin")
				{
					<center class="col-4" >
						<a style="text-decoration: none" class=" text-dark" asp-area="" asp-controller="Users" asp-action="Measures">Measurements</a>
					</center>
				}
		</div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FinalProject/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinalProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>